<a href="https://colab.research.google.com/github/Magwict/Hands-on-Large-Language-Model-Code-/blob/main/Chapter_5_%E4%B8%BB%E9%A2%98%E5%BB%BA%E6%A8%A1%E5%B9%B6%E5%8F%AF%E8%A7%86%E5%8C%96.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%capture
!pip install bertopic datasets openai datamapplot

In [ ]:
!pip install --upgrade datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.1.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.19.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.35.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.12.15)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2025.8.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [ ]:
#从hugging face下载数据集
from datasets import load_dataset
dataset = load_dataset("maartengr/arxiv_nlp")["train"]

#提取元数据
abstracts = dataset["Abstracts"]
titles = dataset["Titles"]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/617 [00:00<?, ?B/s]

data.csv:   0%|          | 0.00/53.2M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
from sentence_transformers import SentenceTransformer

#为每一个摘要创造嵌入
embedding_model = SentenceTransformer("thenlper/gte-small")
embeddings = embedding_model.encode(abstracts,show_progress_bar=True)

modules.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/583 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/66.7M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/394 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/1405 [00:00<?, ?it/s]

In [ ]:
from umap import UMAP

#将输入嵌入从384维降低到2维,便于后续可视化
umap_model = UMAP(
    n_components=2,min_dist=0.0,metric='cosine',random_state=42
)

reduced_embeddings = umap_model.fit_transform(embeddings)

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

In [ ]:
from hdbscan import HDBSCAN

#拟合模型并提取聚类
hdbscan_model = HDBSCAN(
    min_cluster_size=50,
    metric='euclidean',
    cluster_selection_method='eom'
).fit(reduced_embeddings)

clusters = hdbscan_model.labels_ #返回每个样本的簇标签，格式为整数数组

#打印聚类结果，簇的数量
len(set(clusters))

/usr/local/lib/python3.12/dist-packages/hdbscan/plots.py:448: SyntaxWarning: invalid escape sequence '\l'
  axis.set_ylabel('$\lambda$ value')
/usr/local/lib/python3.12/dist-packages/hdbscan/robust_single_linkage_.py:175: SyntaxWarning: invalid escape sequence '\{'
  $max \{ core_k(a), core_k(b), 1/\alpha d(a,b) \}$.
/usr/local/lib/python3.12/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

155

In [ ]:
from bertopic import BERTopic

#用之前定义的模型训练新模型：使用 BERTopic 库训练一个主题建模模型
topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model, #降维模型，可以用PCA替换UMAP
    hdbscan_model=hdbscan_model, #聚类模型，可以用k-means替换hdbscan
    verbose=True
).fit(abstracts,embeddings) #输入摘要和高维向量

2025-09-24 18:06:56,385 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-09-24 18:07:37,301 - BERTopic - Dimensionality - Completed ✓
2025-09-24 18:07:37,303 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-09-24 18:07:38,983 - BERTopic - Cluster - Completed ✓
2025-09-24 18:07:38,996 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-09-24 18:07:42,876 - BERTopic - Representation - Completed ✓

In [ ]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,12858,-1_of_the_and_to,"[of, the, and, to, in, we, that, for, on, lang...",[ With the proliferation of its applications ...
1,0,2545,0_speech_asr_recognition_end,"[speech, asr, recognition, end, acoustic, spok...",[ Recent advances in text-to-speech (TTS) led...
2,1,1441,1_medical_clinical_biomedical_patient,"[medical, clinical, biomedical, patient, notes...",[ Recent years have seen particular interest ...
3,2,1252,2_dialogue_response_dialog_responses,"[dialogue, response, dialog, responses, conver...",[ While neural conversation models have shown...
4,3,948,3_summarization_summaries_summary_abstractive,"[summarization, summaries, summary, abstractiv...",[ Sentence summarization shortens given texts...
...,...,...,...,...,...
150,149,51,149_table_tables_tabular_reasoning,"[table, tables, tabular, reasoning, column, ll...","[ Table reasoning, which aims to generate the..."
151,150,51,150_cqa_question_answer_community,"[cqa, question, answer, community, questions, ...",[ Community Question Answering (CQA) is a wel...
152,151,50,151_arabic_sentiment_analysis_dialect,"[arabic, sentiment, analysis, dialect, sa, msa...","[ Social media such as Twitter, Facebook, etc..."
153,152,50,152_oie_openie_extraction_ie,"[oie, openie, extraction, ie, open, extraction...",[ Open Information Extraction (OIE) is the ta...
154,153,50,153_table_tables_qa_question,"[table, tables, qa, question, answering, hybri...",[ Recent advances in tabular question answeri...

In [ ]:
topic_model.get_topic(0)

[('speech', np.float64(0.026446167075355062)),
 ('asr', np.float64(0.0175609577099786)),
 ('recognition', np.float64(0.012625284787080655)),
 ('end', np.float64(0.009497813473863692)),
 ('acoustic', np.float64(0.008789331289606784)),
 ('spoken', np.float64(0.0068389241751667966)),
 ('audio', np.float64(0.0066426001073515316)),
 ('speaker', np.float64(0.006349509043228593)),
 ('the', np.float64(0.006330059252104944)),
 ('model', np.float64(0.006275455502393749))]

# Representation Models

In [ ]:
#保存原始模型（没有使用生成模型），以便后续对比分析
from copy import deepcopy
original_topics = deepcopy(topic_model.topic_representations_)

In [ ]:
#可视化主题词差异
def topic_differences(model,original_topics,nr_topics=5):
  """Show the differences in topic representations between two models"""
  df = pd.DataFrame(columns=["Topic","Original","Updated"])
  for topic in range(nr_topics):

    #提取两个模型中每个簇的前五个词
    og_words = "|".join(list(zip(*original_topics[topic]))[0][:5])
    new_words = "|".join(list(zip(*model.get_topic(topic)))[0][:5])
    df.loc[len(df)] = [topic,og_words,new_words]

  return df

In [ ]:
import pandas as pd
from bertopic.representation import KeyBERTInspired

#使用KeyBERTInspired更新主题表示，优化BERTopic的表示
representation_model = KeyBERTInspired()

#topic_model是之前用BERTopic库训练的主题建模模型
topic_model.update_topics(abstracts,representation_model=representation_model)

#展示主题差异
topic_differences(topic_model,original_topics)

,Topic,Original,Updated
0,0,speech|asr|recognition|end|acoustic,phonetic|speech|transcription|language|spoken
1,1,medical|clinical|biomedical|patient|notes,nlp|clinical|ehr|ehrs|annotated
2,2,dialogue|response|dialog|responses|conversation,dialogues|dialogue|conversational|conversation...
3,3,summarization|summaries|summary|abstractive|do...,summarization|summarizers|summaries|summary|ab...
4,4,translation|nmt|machine|neural|bleu,translation|translating|translate|translations...

In [ ]:
from bertopic.representation import MaximalMarginalRelevance

# Update our topic representations to MaximalMarginalRelevance
representation_model = MaximalMarginalRelevance(diversity=0.5)
topic_model.update_topics(abstracts, representation_model=representation_model)

# Show topic differences
topic_differences(topic_model, original_topics)

,Topic,Original,Updated
0,0,speech|asr|recognition|end|acoustic,asr|audio|speaker|model|slu
1,1,medical|clinical|biomedical|patient|notes,clinical|biomedical|patient|healthcare|extraction
2,2,dialogue|response|dialog|responses|conversation,response|systems|conversational|generation|dia...
3,3,summarization|summaries|summary|abstractive|do...,summarization|document|extractive|rouge|factual
4,4,translation|nmt|machine|neural|bleu,translation|nmt|neural|bleu|parallel

In [ ]:
#from transformers import pipeline
#from bertopic.representation import TextGeneration

#prompt = """I have a topic that contains the following documents:
#[DOCUMENTS]

#The topic is described by the following keywords: '[KEYWORDS]'.

#Based on the documents and keywords, what is this topic about?"""

# Update our topic representations using Flan-T5
#generator = pipeline("text2text-generation", model="google/flan-t5-small")
#representation_model = TextGeneration(
#    generator, prompt=prompt, doc_length=50, tokenizer="whitespace"
#)
#topic_model.update_topics(abstracts, representation_model=representation_model)

# Show topic differences
#topic_differences(topic_model, original_topics)

In [ ]:
import openai
from bertopic.representation import OpenAI

prompt = """
I have a topic that contains the following documents:
[DOCUMENTS]

The topic is described by the following keywords: [KEYWORDS]

Based on the information above, extract a short topic label in the following
format:
topic: <short topic label>
"""
# Update our topic representations using GPT-3.5
client = openai.OpenAI(api_key="YOURKEY", base_url="https://api.deepseek.com")
representation_model = OpenAI(
  client, model="deepseek-chat", exponential_backoff=True, chat=True,
prompt=prompt
)
topic_model.update_topics(abstracts, representation_model=representation_model)

# Show topic differences
topic_differences(topic_model, original_topics)

100%|██████████| 155/155 [09:29<00:00,  3.67s/it]

,Topic,Original,Updated
0,0,speech|asr|recognition|end|acoustic,Advances in Automatic Speech Recognition and S...
1,1,medical|clinical|biomedical|patient|notes,Clinical Note Information Extraction in Health...
2,2,dialogue|response|dialog|responses|conversation,Dialogue System Optimization and Learning Methods
3,3,summarization|summaries|summary|abstractive|do...,Unsupervised and Abstractive Text Summarizatio...
4,4,translation|nmt|machine|neural|bleu,Enhancing Neural Machine Translation with Data...

In [ ]:
#获取每个文档（每篇论文）所属的簇cluster
doc_topics = topic_model.topics_

# 使用GPT生成的主题标签替换数字标签
topic_labels = topic_model.generate_topic_labels()  # 获取生成的主题标签

In [ ]:
reduced_embeddings.shape

(44949, 2)

In [ ]:
# 获取主题信息
topic_info = topic_model.get_topic_info()

# 查看生成的主题标签
print(topic_info[['Topic', 'Name']])

     Topic                                               Name
0       -1  -1_Cross-modal transfer learning and neural ne...
1        0  0_Advances in Automatic Speech Recognition and...
2        1  1_Clinical Note Information Extraction in Heal...
3        2  2_Dialogue System Optimization and Learning Me...
4        3  3_Unsupervised and Abstractive Text Summarizat...
..     ...                                                ...
150    149     149_Table Reasoning with Large Language Models
151    150  150_Community Question Answering (CQA) Researc...
152    151      151_Arabic Sentiment Analysis on Social Media
153    152  152_Open Information Extraction (OIE) systems ...
154    153         153_Table Question Answering and Retrieval

[155 rows x 2 columns]

In [ ]:
# 获取主题信息并创建映射（截断为15个字符）
topic_label_mapping = {}
for _, row in topic_info.iterrows():
    topic_id = row['Topic']
    generated_label = row['Name']
    # 截断为前15个字符，如果超过15个字符添加省略号
    truncated_label = generated_label[:25] + "..." if len(generated_label) > 25 else generated_label
    topic_label_mapping[topic_id] = truncated_label

In [ ]:
print("主题标签映射：")
print(topic_label_mapping)

主题标签映射：
{-1: '-1_Cross-modal transfer l...', 0: '0_Advances in Automatic S...', 1: '1_Clinical Note Informati...', 2: '2_Dialogue System Optimiz...', 3: '3_Unsupervised and Abstra...', 4: '4_Enhancing Neural Machin...', 5: '5_Unsupervised Question-A...', 6: '6_Gender Bias Mitigation ...', 7: '7_Cross-lingual Transfer ...', 8: '8_Advances in Named Entit...', 9: '9_Advances in Relation Ex...', 10: '10_Multimodal Vision-Lang...', 11: '11_dependency parsing and...', 12: '12_Word Meta-Embeddings a...', 13: '13_Advances in Natural La...', 14: '14_Legal AI and Language ...', 15: '15_Advances in Text Class...', 16: '16_Compositional Distribu...', 17: '17_Machine Translation Qu...', 18: '18_Human and Model Explan...', 19: "19_Zipf's linguistic laws...", 20: '20_Interpretable Multi-Ho...', 21: '21_Scientific Literature ...', 22: '22_Knowledge Graph Comple...', 23: '23_Automated hate speech ...', 24: '24_Parameter-Efficient Fi...', 25: '25_controlled text genera...', 26: '26_Aspect-Based Sentiment...', 27: '27_Counterfactual Data Au...', 28: '28_Adversarial attacks an...', 29: '29_Automated Fake News De...', 30: '30_Machine Reading Compre...', 31: '31_Offensive Language Det...', 32: '32_Prompt-based Few-shot ...', 33: '33_Instruction Tuning and...', 34: '34_Text Simplification Te...', 35: '35_Event Extraction Metho...', 36: '36_Advances and Evaluatio...', 37: '37_Computational Argument...', 38: '38_Chain-of-Thought reaso...', 39: '39_Efficient Transformer ...', 40: '40_Commonsense Knowledge ...', 41: '41_Word Sense Disambiguat...', 42: '42_Advances in Neural Cor...', 43: '43_Brain-Language Model A...', 44: '44_Automated Fact-Checkin...', 45: '45_Authorship Analysis an...', 46: '46_Entity Linking Approac...', 47: '47_Code Generation and Re...', 48: '48_Text-to-SQL parsing an...', 49: '49_Computational Analysis...', 50: '50_Safety Vulnerabilities...', 51: '51_Arabic Dialect Natural...', 52: '52_Financial Applications...', 53: '53_Automated Mental Healt...', 54: '54_Causal and Temporal Re...', 55: '55_Sentiment Analysis and...', 56: '56_Automatic Story Genera...', 57: '57_Evaluating and Enhanci...', 58: '58_In-Context Learning in...', 59: '59_Grammatical Error Corr...', 60: '60_Dialogue State Trackin...', 61: '61_Text Style Transfer Me...', 62: '62_Reinforcement Learning...', 63: '63_Knowledge Distillation...', 64: '64_Emotion Analysis and E...', 65: '65_Hallucination Detectio...', 66: '66_Computational Analysis...', 67: '67_Advances in Discourse ...', 68: '68_Intent Detection and D...', 69: '69_Automatic Evaluation M...', 70: '70_Non-Autoregressive Mac...', 71: '71_Sanskrit and Indic Lan...', 72: '72_AI-generated text dete...', 73: '73_Chinese classical poet...', 74: '74_Paraphrase Generation ...', 75: '75_multimodal visual-grou...', 76: '76_Personalized Dialogue ...', 77: '77_Continual Learning and...', 78: '78_Computational Models o...', 79: '79_Contrastive Learning f...', 80: '80_Knowledge Editing in L...', 81: '81_Keyphrase Extraction a...', 82: '82_Efficient Compression ...', 83: '83_Data Augmentation for ...', 84: '84_Privacy-Preserving Lan...', 85: '85_Neural Approaches to T...', 86: '86_Advances in Abstract M...', 87: '87_Computational Sarcasm ...', 88: '88_Masking strategies in ...', 89: '89_Empathetic Dialogue Re...', 90: '90_Automated Radiology Re...', 91: '91_Layout-enhanced docume...', 92: '92_Computational Morpholo...', 93: '93_abstractive meeting su...', 94: '94_Cross-lingual and cros...', 95: '95_NLP research for low-r...', 96: '96_Computational Approach...', 97: '97_Advances and Challenge...', 98: '98_parsing algorithms for...', 99: '99_Active Learning Strate...', 100: '100_Stance Detection in S...', 101: '101_Probing linguistic in...', 102: '102_Neural Semantic Role ...', 103: '103_Automated Prompt Opti...', 104: '104_Geospatial Text Data ...', 105: '105_Linguistic Annotation...', 106: '106_Automated Essay Scori...', 107: '107_Social Media Sentimen...', 108: '108_Adversarial Robustnes...', 109: '109_Sign Language Transla...', 110: '110_Automated Taxonomy Ex...', 111: '111_E-commerce product in...', 112: '112_Crisis-related social...', 113: '113_Automated detection a...', 114: '114_Document-Level Contex...', 115: '115_Part-of-speech taggin...', 116: '116_Multimodal Machine Tr...', 117: '117_Evaluating Personalit...', 118: '118_Calibration methods a...', 119: '119_Multimodal Speech Emo...', 120: '120_Word and Subword Alig...', 121: '121_Entity Alignment in K...', 122: '122_Computational Metapho...', 123: '123_Computational Analysi...', 124: '124_Multimodal Emotion Re...', 125: '125_Computational Humor A...', 126: '126_Language identificati...', 127: '127_Advances and Challeng...', 128: '128_Reinforcement learnin...', 129: '129_Advances in Dense Ret...', 130: '130_Mixture of Experts (M...', 131: '131_Automated Cognate Det...', 132: '132_Rumor stance and vera...', 133: '133_Computational Modelin...', 134: '134_Detection and analysi...', 135: '135_Parallel Corpora Mini...', 136: '136_Chinese Spelling Corr...', 137: '137_Dialogue Act Recognit...', 138: '138_Neural Sequence Label...', 139: '139_Code-Mixed Sentiment ...', 140: '140_Fine-grained entity t...', 141: '141_Efficient Transformer...', 142: '142_Automated Job Matchin...', 143: '143_Propaganda Detection ...', 144: '144_Emoji semantics and p...', 145: '145_Enhancing Mathematica...', 146: '146_Computational analysi...', 147: '147_Opinion Summarization...', 148: '148_Improving GAN-based t...', 149: '149_Table Reasoning with ...', 150: '150_Community Question An...', 151: '151_Arabic Sentiment Anal...', 152: '152_Open Information Extr...', 153: '153_Table Question Answer...'}

In [ ]:
# 获取主题频率，找到前40个最大的簇
topic_info = topic_model.get_topic_info()
top_40_topics = topic_info[topic_info.Topic != -1].head(40)['Topic'].tolist()

print("前40个簇的编号:", top_40_topics)

前40个簇的编号: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]

In [ ]:
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,12858,-1_Cross-modal transfer learning and neural ne...,[Cross-modal transfer learning and neural netw...,[ With the proliferation of its applications ...
1,0,2545,0_Advances in Automatic Speech Recognition and...,[Advances in Automatic Speech Recognition and ...,[ Recent advances in text-to-speech (TTS) led...
2,1,1441,1_Clinical Note Information Extraction in Heal...,[Clinical Note Information Extraction in Healt...,[ Recent years have seen particular interest ...
3,2,1252,2_Dialogue System Optimization and Learning Me...,[Dialogue System Optimization and Learning Met...,[ While neural conversation models have shown...
4,3,948,3_Unsupervised and Abstractive Text Summarizat...,[Unsupervised and Abstractive Text Summarizati...,[ Sentence summarization shortens given texts...
...,...,...,...,...,...
150,149,51,149_Table Reasoning with Large Language Models,[Table Reasoning with Large Language Models],"[ Table reasoning, which aims to generate the..."
151,150,51,150_Community Question Answering (CQA) Researc...,[Community Question Answering (CQA) Research a...,[ Community Question Answering (CQA) is a wel...
152,151,50,151_Arabic Sentiment Analysis on Social Media,[Arabic Sentiment Analysis on Social Media],"[ Social media such as Twitter, Facebook, etc..."
153,152,50,152_Open Information Extraction (OIE) systems ...,[Open Information Extraction (OIE) systems and...,[ Open Information Extraction (OIE) is the ta...
154,153,50,153_Table Question Answering and Retrieval,[Table Question Answering and Retrieval],[ Recent advances in tabular question answeri...

In [ ]:
# 过滤数据：只保留属于前20个簇的点和噪声点(-1)
indices_to_keep = []
filtered_labels = []

for i, topic_id in enumerate(topic_model.topics_):
    if topic_id in top_40_topics or topic_id == -1:
        indices_to_keep.append(i)
        filtered_labels.append(topic_id)

print(indices_to_keep) #文档的序列
print(filtered_labels) #文档对应的聚类编号

[2, 3, 7, 10, 11, 12, 13, 14, 16, 17, 19, 20, 21, 22, 23, 24, 26, 28, 30, 31, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 47, 48, 50, 51, 52, 53, 55, 58, 59, 60, 62, 63, 64, 65, 66, 67, 68, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 104, 106, 108, 109, 111, 112, 113, 114, 115, 116, 118, 119, 120, 126, 127, 128, 130, 131, 132, 133, 134, 137, 139, 140, 141, 142, 144, 145, 150, 151, 157, 158, 159, 160, 161, 162, 163, 165, 166, 167, 170, 171, 173, 174, 175, 176, 179, 180, 181, 182, 184, 185, 186, 188, 189, 190, 191, 193, 195, 197, 200, 203, 204, 205, 206, 207, 210, 211, 217, 218, 220, 221, 222, 223, 224, 225, 226, 227, 229, 231, 232, 233, 234, 235, 236, 237, 238, 239, 241, 242, 243, 245, 247, 248, 250, 251, 255, 256, 257, 258, 260, 261, 262, 263, 264, 265, 266, 267, 269, 271, 272, 273, 274, 275, 276, 277, 278, 279, 283, 285, 286, 287, 288, 289, 297, 298, 299, 300, 303, 304, 310, 312, 315, 316, 317, 318, 321, 322, 323, 325, 327, 328, 329, 330, 331, 332, 333, 335, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 379, 380, 381, 383, 385, 388, 390, 391, 392, 393, 394, 395, 398, 399, 400, 401, 402, 404, 405, 409, 411, 412, 413, 415, 416, 417, 420, 421, 422, 423, 426, 427, 428, 429, 431, 432, 433, 435, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 448, 452, 453, 454, 455, 460, 461, 464, 465, 466, 469, 470, 471, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 487, 488, 489, 490, 491, 492, 493, 494, 502, 503, 506, 508, 509, 510, 511, 512, 513, 514, 515, 517, 519, 520, 521, 523, 529, 530, 532, 533, 534, 536, 537, 538, 542, 544, 545, 546, 547, 548, 550, 551, 554, 555, 558, 559, 560, 561, 564, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 585, 587, 588, 589, 590, 591, 594, 595, 596, 597, 598, 599, 600, 601, 603, 605, 606, 607, 608, 609, 610, 611, 612, 613, 615, 617, 618, 619, 620, 621, 623, 625, 626, 627, 628, 629, 630, 631, 634, 636, 638, 639, 642, 643, 644, 645, 646, 650, 651, 654, 655, 657, 658, 659, 661, 662, 663, 664, 665, 666, 668, 671, 672, 673, 674, 675, 676, 677, 679, 680, 681, 682, 683, 684, 686, 687, 688, 690, 692, 693, 695, 696, 698, 699, 700, 701, 703, 704, 706, 710, 713, 714, 716, 717, 718, 719, 721, 722, 723, 724, 725, 727, 729, 730, 731, 732, 733, 734, 736, 737, 738, 740, 741, 745, 746, 747, 748, 751, 752, 754, 758, 760, 762, 764, 765, 766, 767, 770, 771, 772, 774, 775, 778, 780, 782, 783, 784, 785, 789, 791, 792, 793, 794, 795, 796, 797, 798, 799, 801, 803, 806, 807, 808, 811, 812, 813, 814, 816, 818, 820, 821, 822, 823, 824, 826, 828, 830, 831, 832, 834, 836, 837, 839, 840, 841, 844, 845, 846, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 876, 877, 879, 880, 882, 883, 884, 886, 887, 888, 890, 891, 892, 893, 894, 895, 897, 898, 899, 903, 904, 905, 906, 907, 909, 910, 911, 912, 913, 914, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 933, 937, 939, 940, 942, 943, 944, 946, 947, 948, 949, 950, 951, 952, 953, 954, 956, 957, 958, 960, 961, 962, 963, 965, 967, 968, 971, 972, 973, 974, 975, 976, 977, 978, 980, 981, 982, 983, 984, 985, 986, 988, 990, 991, 992, 995, 998, 999, 1000, 1001, 1002, 1004, 1005, 1007, 1008, 1009, 1010, 1012, 1013, 1014, 1016, 1018, 1021, 1022, 1024, 1025, 1026, 1027, 1028, 1029, 1033, 1034, 1035, 1036, 1038, 1039, 1041, 1042, 1043, 1044, 1046, 1047, 1048, 1050, 1051, 1052, 1055, 1057, 1058, 1059, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1069, 1070, 1072, 1074, 1075, 1077, 1078, 1081, 1082, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1100, 1101, 1103, 1105, 1106, 1107, 1108, 1109, 1111, 1112, 1113, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1128, 1129, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1139, 1140, 1141, 1143, 1144, 1145, 1147, 1148, 1149, 1151, 1153, 1155, 1156, 1157, 1160, 1161, 1162, 1163, 1164, 1166, 1167, 1168, 1169, 1171, 1172, 1173, 1175, 1177, 1178, 1179, 1180, 1181, 1184, 1185, 1186, 1187, 1188, 1190, 1191, 1192, 1194, 1195, 1196, 1198, 1199, 1200, 1201, 1203, 1208, 1209, 1212, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1231, 1232, 1233, 1234, 1236, 1237, 1238, 1240, 1241, 1242, 1243, 1244, 1246, 1247, 1249, 1250, 1251, 1252, 1253, 1255, 1256, 1258, 1259, 1260, 1261, 1262, 1264, 1266, 1267, 1268, 1269, 1270, 1272, 1275, 1276, 1277, 1280, 1281, 1283, 1284, 1286, 1287, 1288, 1289, 1291, 1292, 1293, 1294, 1295, 1296, 1298, 1299, 1301, 1303, 1305, 1306, 1307, 1308, 1311, 1312, 1314, 1315, 1319, 1320, 1322, 1323, 1324, 1325, 1326, 1327, 1330, 1331, 1332, 1333, 1334, 1335, 1337, 1338, 1340, 1342, 1343, 1344, 1345, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1379, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1390, 1392, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1412, 1413, 1415, 1418, 1419, 1420, 1421, 1422, 1423, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1433, 1434, 1435, 1437, 1438, 1440, 1441, 1442, 1444, 1445, 1446, 1448, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1460, 1461, 1462, 1463, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1477, 1479, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1493, 1496, 1497, 1498, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1514, 1515, 1516, 1517, 1518, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1531, 1532, 1533, 1535, 1536, 1538, 1540, 1541, 1543, 1544, 1545, 1546, 1552, 1553, 1554, 1556, 1558, 1560, 1562, 1563, 1564, 1565, 1567, 1568, 1569, 1570, 1574, 1576, 1577, 1579, 1580, 1581, 1582, 1583, 1585, 1587, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1618, 1619, 1621, 1622, 1624, 1625, 1626, 1627, 1628, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1649, 1650, 1651, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1671, 1674, 1676, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1689, 1692, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1732, 1733, 1734, 1736, 1737, 1738, 1739, 1740, 1742, 1743, 1744, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1763, 1764, 1765, 1766, 1769, 1770, 1771, 1774, 1775, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1786, 1787, 1789, 1790, 1793, 1794, 1796, 1798, 1799, 1801, 1802, 1804, 1805, 1809, 1810, 1811, 1813, 1815, 1816, 1817, 1818, 1819, 1821, 1822, 1823, 1824, 1825, 1827, 1828, 1830, 1831, 1832, 1835, 1837, 1838, 1839, 1840, 1841, 1843, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1859, 1860, 1861, 1863, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1895, 1896, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1908, 1909, 1910, 1911, 1912, 1913, 1915, 1916, 1917, 1918, 1920, 1921, 1922, 1923, 1925, 1926, 1927, 1930, 1931, 1932, 1933, 1935, 1937, 1938, 1939, 1942, 1943, 1944, 1947, 1948, 1950, 1951, 1952, 1953, 1955, 1956, 1957, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1969, 1970, 1972, 1974, 1976, 1980, 1981, 1982, 1983, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1996, 1998, 2000, 2001, 2002, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2018, 2019, 2020, 2021, 2022, 2023, 2025, 2026, 2027, 2028, 2030, 2031, 2033, 2034, 2036, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2046, 2048, 2049, 2050, 2053, 2054, 2057, 2058, 2059, 2060, 2061, 2062, 2064, 2065, 2066, 2068, 2070, 2071, 2072, 2073, 2076, 2077, 2078, 2079, 2081, 2083, 2084, 2085, 2086, 2087, 2089, 2090, 2091, 2092, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2104, 2105, 2106, 2107, 2109, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2119, 2120, 2121, 2122, 2125, 2126, 2127, 2128, 2131, 2132, 2135, 2137, 2138, 2139, 2140, 2143, 2145, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2155, 2156, 2157, 2158, 2159, 2161, 2164, 2165, 2166, 2167, 2169, 2171, 2173, 2174, 2176, 2178, 2179, 2181, 2182, 2183, 2184, 2185, 2186, 2188, 2189, 2190, 2191, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2204, 2205, 2206, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2218, 2219, 2220, 2221, 2223, 2224, 2225, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2235, 2236, 2237, 2238, 2239, 2241, 2242, 2243, 2245, 2246, 2248, 2249, 2251, 2252, 2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2273, 2274, 2276, 2277, 2282, 2284, 2285, 2287, 2288, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2302, 2303, 2305, 2306, 2307, 2308, 2311, 2312, 2313, 2315, 2316, 2317, 2318, 2320, 2321, 2323, 2324, 2325, 2326, 2328, 2331, 2332, 2333, 2334, 2335, 2336, 2338, 2340, 2342, 2344, 2345, 2346, 2347, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2357, 2358, 2359, 2360, 2361, 2364, 2365, 2368, 2370, 2371, 2372, 2374, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2384, 2385, 2386, 2387, 2388, 2389, 2391, 2393, 2396, 2399, 2401, 2402, 2404, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2415, 2416, 2417, 2418, 2421, 2422, 2423, 2427, 2428, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2439, 2440, 2442, 2443, 2444, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2463, 2464, 2465, 2466, 2468, 2469, 2470, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2482, 2484, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495, 2498, 2499, 2500, 2501, 2502, 2504, 2506, 2507, 2508, 2511, 2513, 2514, 2516, 2519, 2521, 2522, 2524, 2525, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2538, 2539, 2540, 2541, 2543, 2544, 2548, 2549, 2550, 2551, 2554, 2555, 2556, 2561, 2562, 2563, 2564, 2566, 2567, 2568, 2569, 2572, 2574, 2575, 2576, 2577, 2578, 2579, 2581, 2582, 2583, 2584, 2587, 2589, 2590, 2591, 2592, 2594, 2595, 2596, 2597, 2598, 2599, 2600, 2601, 2602, 2604, 2606, 2610, 2612, 2614, 2615, 2616, 2617, 2618, 2621, 2623, 2625, 2626, 2628, 2629, 2630, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2643, 2644, 2645, 2646, 2647, 2648, 2649, 2650, 2651, 2653, 2654, 2656, 2657, 2658, 2661, 2662, 2663, 2666, 2667, 2668, 2669, 2671, 2673, 2675, 2676, 2678, 2680, 2682, 2683, 2685, 2687, 2688, 2690, 2691, 2692, 2693, 2695, 2696, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2709, 2710, 2711, 2712, 2714, 2715, 2716, 2718, 2719, 2720, 2721, 2722, 2724, 2725, 2727, 2728, 2731, 2732, 2734, 2736, 2737, 2738, 2739, 2741, 2742, 2743, 2744, 2745, 2746, 2749, 2750, 2752, 2754, 2755, 2756, 2757, 2758, 2759, 2763, 2764, 2765, 2766, 2767, 2768, 2772, 2773, 2774, 2777, 2778, 2779, 2780, 2782, 2783, 2784, 2785, 2786, 2787, 2788, 2790, 2792, 2793, 2795, 2796, 2797, 2798, 2799, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2810, 2811, 2812, 2814, 2815, 2816, 2818, 2819, 2821, 2822, 2823, 2824, 2825, 2826, 2827, 2829, 2830, 2831, 2833, 2834, 2835, 2836, 2837, 2838, 2839, 2841, 2842, 2843, 2845, 2846, 2847, 2848, 2849, 2850, 2851, 2852, 2853, 2854, 2855, 2856, 2857, 2858, 2860, 2861, 2863, 2864, 2865, 2866, 2868, 2869, 2871, 2872, 2873, 2875, 2876, 2877, 2878, 2879, 2880, 2881, 2882, 2883, 2884, 2889, 2890, 2892, 2895, 2896, 2897, 2898, 2899, 2900, 2903, 2904, 2905, 2907, 2910, 2911, 2912, 2913, 2914, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923, 2924, 2925, 2926, 2929, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2938, 2940, 2941, 2942, 2943, 2945, 2946, 2947, 2949, 2950, 2951, 2952, 2953, 2955, 2957, 2958, 2959, 2960, 2962, 2964, 2965, 2967, 2968, 2969, 2970, 2972, 2973, 2974, 2976, 2977, 2978, 2979, 2980, 2981, 2983, 2984, 2985, 2986, 2987, 2990, 2991, 2992, 2993, 2995, 2997, 2998, 2999, 3000, 3001, 3003, 3004, 3005, 3007, 3008, 3009, 3010, 3011, 3012, 3019, 3020, 3021, 3023, 3024, 3026, 3027, 3028, 3029, 3032, 3035, 3036, 3037, 3038, 3039, 3041, 3042, 3044, 3045, 3046, 3047, 3048, 3049, 3050, 3052, 3055, 3056, 3057, 3058, 3059, 3061, 3062, 3068, 3069, 3070, 3071, 3073, 3075, 3076, 3077, 3078, 3079, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3094, 3095, 3097, 3098, 3099, 3100, 3101, 3102, 3103, 3105, 3106, 3107, 3108, 3109, 3110, 3112, 3113, 3114, 3115, 3116, 3118, 3119, 3120, 3122, 3123, 3124, 3125, 3127, 3128, 3129, 3130, 3131, 3134, 3135, 3136, 3137, 3138, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3148, 3150, 3152, 3153, 3156, 3158, 3160, 3161, 3163, 3166, 3167, 3168, 3169, 3171, 3172, 3174, 3175, 3176, 3177, 3179, 3181, 3182, 3183, 3186, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3197, 3198, 3199, 3200, 3201, 3203, 3204, 3205, 3206, 3208, 3209, 3211, 3215, 3217, 3218, 3222, 3223, 3225, 3226, 3227, 3228, 3229, 3230, 3231, 3235, 3236, 3237, 3240, 3241, 3244, 3246, 3247, 3248, 3249, 3251, 3252, 3253, 3254, 3255, 3256, 3257, 3259, 3261, 3262, 3263, 3264, 3265, 3266, 3268, 3269, 3271, 3272, 3274, 3275, 3277, 3278, 3280, 3281, 3283, 3284, 3285, 3286, 3287, 3288, 3290, 3291, 3292, 3293, 3294, 3296, 3297, 3298, 3299, 3300, 3301, 3302, 3303, 3304, 3306, 3307, 3309, 3312, 3313, 3316, 3317, 3321, 3322, 3324, 3325, 3326, 3327, 3331, 3332, 3333, 3334, 3335, 3336, 3339, 3340, 3342, 3343, 3344, 3345, 3347, 3349, 3350, 3351, 3353, 3356, 3358, 3360, 3362, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3376, 3377, 3378, 3382, 3383, 3385, 3386, 3387, 3388, 3389, 3390, 3392, 3396, 3397, 3399, 3401, 3404, 3406, 3407, 3408, 3409, 3410, 3413, 3414, 3415, 3416, 3417, 3418, 3419, 3423, 3425, 3426, 3428, 3429, 3430, 3431, 3432, 3433, 3434, 3437, 3438, 3439, 3440, 3441, 3443, 3444, 3445, 3446, 3447, 3448, 3449, 3452, 3453, 3454, 3456, 3457, 3459, 3462, 3464, 3467, 3469, 3471, 3472, 3480, 3481, 3485, 3486, 3488, 3492, 3493, 3495, 3498, 3500, 3501, 3502, 3503, 3505, 3506, 3508, 3509, 3510, 3511, 3512, 3513, 3518, 3519, 3520, 3521, 3522, 3523, 3524, 3525, 3527, 3528, 3529, 3530, 3531, 3533, 3534, 3535, 3537, 3538, 3539, 3540, 3541, 3542, 3543, 3546, 3547, 3548, 3549, 3550, 3552, 3553, 3554, 3555, 3556, 3557, 3558, 3559, 3560, 3561, 3562, 3563, 3564, 3565, 3567, 3568, 3570, 3571, 3572, 3574, 3575, 3577, 3578, 3580, 3581, 3582, 3586, 3587, 3588, 3589, 3590, 3591, 3592, 3593, 3594, 3595, 3597, 3598, 3600, 3601, 3602, 3603, 3604, 3605, 3606, 3607, 3608, 3609, 3610, 3611, 3612, 3613, 3615, 3616, 3617, 3618, 3619, 3620, 3621, 3623, 3624, 3625, 3627, 3628, 3631, 3632, 3633, 3634, 3635, 3636, 3638, 3639, 3640, 3641, 3642, 3643, 3644, 3647, 3648, 3650, 3653, 3655, 3656, 3657, 3658, 3659, 3660, 3661, 3662, 3663, 3665, 3666, 3669, 3670, 3672, 3673, 3674, 3675, 3676, 3677, 3679, 3681, 3682, 3683, 3684, 3687, 3688, 3689, 3693, 3694, 3695, 3696, 3697, 3698, 3699, 3701, 3702, 3703, 3705, 3706, 3707, 3709, 3710, 3711, 3712, 3713, 3715, 3717, 3718, 3719, 3720, 3722, 3724, 3725, 3726, 3727, 3728, 3729, 3730, 3731, 3732, 3733, 3734, 3735, 3736, 3737, 3739, 3741, 3742, 3743, 3744, 3746, 3747, 3748, 3749, 3750, 3751, 3753, 3754, 3755, 3756, 3757, 3758, 3759, 3761, 3762, 3763, 3764, 3765, 3766, 3767, 3768, 3772, 3773, 3775, 3776, 3777, 3778, 3779, 3780, 3782, 3783, 3784, 3785, 3786, 3787, 3788, 3789, 3790, 3791, 3792, 3794, 3797, 3798, 3800, 3801, 3802, 3803, 3804, 3805, 3806, 3807, 3808, 3810, 3811, 3813, 3814, 3818, 3819, 3820, 3823, 3824, 3826, 3829, 3830, 3832, 3833, 3834, 3835, 3836, 3838, 3839, 3842, 3843, 3845, 3847, 3849, 3850, 3851, 3853, 3854, 3857, 3858, 3859, 3860, 3862, 3864, 3865, 3872, 3873, 3875, 3876, 3877, 3878, 3880, 3881, 3882, 3883, 3885, 3887, 3888, 3889, 3891, 3894, 3896, 3897, 3898, 3899, 3900, 3901, 3903, 3904, 3908, 3909, 3910, 3912, 3913, 3914, 3917, 3919, 3920, 3921, 3923, 3925, 3927, 3928, 3929, 3932, 3934, 3935, 3936, 3937, 3941, 3942, 3943, 3944, 3946, 3948, 3950, 3952, 3953, 3954, 3955, 3958, 3959, 3961, 3962, 3964, 3966, 3967, 3968, 3970, 3971, 3972, 3973, 3976, 3977, 3978, 3980, 3981, 3983, 3985, 3986, 3988, 3989, 3990, 3992, 3993, 3995, 3996, 3997, 3998, 4000, 4001, 4002, 4004, 4005, 4006, 4008, 4009, 4011, 4013, 4015, 4016, 4017, 4018, 4019, 4021, 4022, 4023, 4026, 4028, 4029, 4030, 4032, 4033, 4034, 4036, 4038, 4041, 4043, 4045, 4048, 4049, 4052, 4053, 4054, 4056, 4058, 4059, 4060, 4061, 4062, 4063, 4064, 4065, 4066, 4068, 4069, 4070, 4071, 4072, 4074, 4075, 4076, 4077, 4078, 4079, 4080, 4082, 4083, 4085, 4087, 4088, 4090, 4092, 4093, 4094, 4096, 4098, 4099, 4101, 4102, 4106, 4107, 4110, 4112, 4114, 4118, 4119, 4120, 4121, 4123, 4124, 4125, 4128, 4129, 4130, 4132, 4133, 4135, 4138, 4139, 4141, 4142, 4143, 4144, 4146, 4147, 4148, 4149, 4150, 4151, 4153, 4155, 4156, 4157, 4159, 4160, 4161, 4163, 4164, 4165, 4166, 4167, 4169, 4172, 4173, 4174, 4175, 4176, 4179, 4180, 4181, 4184, 4187, 4188, 4189, 4191, 4199, 4200, 4201, 4202, 4204, 4205, 4208, 4209, 4210, 4212, 4213, 4217, 4218, 4219, 4220, 4221, 4222, 4223, 4224, 4226, 4227, 4228, 4229, 4230, 4232, 4233, 4234, 4237, 4238, 4241, 4242, 4244, 4245, 4246, 4247, 4248, 4249, 4250, 4251, 4252, 4253, 4254, 4255, 4257, 4258, 4260, 4262, 4264, 4265, 4266, 4267, 4268, 4269, 4270, 4271, 4272, 4273, 4274, 4275, 4276, 4277, 4278, 4279, 4281, 4282, 4283, 4284, 4285, 4286, 4288, 4289, 4291, 4293, 4294, 4295, 4296, 4297, 4298, 4299, 4301, 4302, 4303, 4304, 4305, 4309, 4310, 4311, 4315, 4316, 4318, 4320, 4322, 4323, 4324, 4325, 4326, 4327, 4328, 4329, 4330, 4331, 4332, 4334, 4335, 4336, 4337, 4338, 4339, 4340, 4341, 4342, 4343, 4344, 4346, 4347, 4349, 4350, 4351, 4352, 4354, 4355, 4356, 4357, 4358, 4359, 4360, 4362, 4363, 4364, 4365, 4367, 4369, 4370, 4371, 4372, 4373, 4374, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4383, 4384, 4385, 4386, 4387, 4388, 4390, 4392, 4393, 4394, 4395, 4396, 4397, 4398, 4399, 4400, 4401, 4402, 4403, 4404, 4405, 4406, 4407, 4409, 4410, 4411, 4413, 4414, 4415, 4416, 4417, 4419, 4421, 4422, 4423, 4424, 4425, 4426, 4429, 4430, 4431, 4432, 4433, 4434, 4435, 4436, 4437, 4439, 4440, 4442, 4443, 4444, 4446, 4448, 4449, 4450, 4451, 4453, 4454, 4455, 4456, 4457, 4459, 4461, 4462, 4463, 4464, 4465, 4466, 4469, 4470, 4471, 4474, 4475, 4476, 4478, 4479, 4480, 4483, 4484, 4485, 4486, 4487, 4489, 4490, 4492, 4493, 4494, 4495, 4496, 4499, 4500, 4501, 4502, 4503, 4504, 4507, 4509, 4510, 4511, 4513, 4514, 4517, 4520, 4521, 4522, 4525, 4526, 4527, 4529, 4530, 4531, 4532, 4534, 4535, 4536, 4537, 4538, 4539, 4540, 4543, 4544, 4545, 4547, 4549, 4550, 4551, 4552, 4553, 4554, 4555, 4556, 4557, 4558, 4559, 4561, 4563, 4565, 4566, 4567, 4568, 4569, 4570, 4571, 4574, 4575, 4576, 4577, 4578, 4579, 4580, 4581, 4582, 4583, 4584, 4586, 4588, 4589, 4590, 4591, 4592, 4593, 4594, 4595, 4598, 4599, 4601, 4602, 4603, 4604, 4605, 4606, 4607, 4609, 4610, 4611, 4613, 4614, 4615, 4617, 4618, 4619, 4621, 4623, 4625, 4626, 4627, 4628, 4630, 4631, 4632, 4633, 4634, 4635, 4638, 4639, 4640, 4641, 4642, 4643, 4644, 4647, 4648, 4649, 4650, 4651, 4653, 4654, 4655, 4657, 4658, 4659, 4660, 4661, 4662, 4663, 4664, 4666, 4667, 4668, 4669, 4670, 4671, 4672, 4676, 4677, 4678, 4680, 4681, 4683, 4684, 4688, 4689, 4691, 4692, 4694, 4695, 4696, 4697, 4698, 4700, 4701, 4703, 4705, 4706, 4707, 4708, 4709, 4712, 4713, 4716, 4717, 4718, 4719, 4720, 4721, 4722, 4723, 4724, 4725, 4726, 4727, 4729, 4730, 4731, 4733, 4734, 4735, 4738, 4739, 4741, 4742, 4743, 4744, 4745, 4746, 4747, 4748, 4749, 4750, 4752, 4753, 4754, 4755, 4756, 4757, 4761, 4762, 4763, 4764, 4765, 4766, 4767, 4768, 4769, 4770, 4773, 4774, 4775, 4776, 4778, 4780, 4781, 4782, 4783, 4784, 4785, 4786, 4787, 4788, 4790, 4791, 4792, 4793, 4794, 4796, 4797, 4798, 4800, 4802, 4804

In [ ]:
# 过滤嵌入向量
filtered_embeddings = reduced_embeddings[indices_to_keep]

In [ ]:
# 直接使用映射字典替换
formatted_labels = []
for label in filtered_labels:
    if label == -1:
        formatted_labels.append("Unlabelled")
    else:
        # 使用大模型生成的标签
        formatted_labels.append(topic_label_mapping.get(label, f"Topic {label}"))

In [ ]:
print(indices_to_keep) #文档的序列
print(formatted_labels) #文档对应的聚类编号

[2, 3, 7, 10, 11, 12, 13, 14, 16, 17, 19, 20, 21, 22, 23, 24, 26, 28, 30, 31, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 47, 48, 50, 51, 52, 53, 55, 58, 59, 60, 62, 63, 64, 65, 66, 67, 68, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 104, 106, 108, 109, 111, 112, 113, 114, 115, 116, 118, 119, 120, 126, 127, 128, 130, 131, 132, 133, 134, 137, 139, 140, 141, 142, 144, 145, 150, 151, 157, 158, 159, 160, 161, 162, 163, 165, 166, 167, 170, 171, 173, 174, 175, 176, 179, 180, 181, 182, 184, 185, 186, 188, 189, 190, 191, 193, 195, 197, 200, 203, 204, 205, 206, 207, 210, 211, 217, 218, 220, 221, 222, 223, 224, 225, 226, 227, 229, 231, 232, 233, 234, 235, 236, 237, 238, 239, 241, 242, 243, 245, 247, 248, 250, 251, 255, 256, 257, 258, 260, 261, 262, 263, 264, 265, 266, 267, 269, 271, 272, 273, 274, 275, 276, 277, 278, 279, 283, 285, 286, 287, 288, 289, 297, 298, 299, 300, 303, 304, 310, 312, 315, 316, 317, 318, 321, 322, 323, 325, 327, 328, 329, 330, 331, 332, 333, 335, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 379, 380, 381, 383, 385, 388, 390, 391, 392, 393, 394, 395, 398, 399, 400, 401, 402, 404, 405, 409, 411, 412, 413, 415, 416, 417, 420, 421, 422, 423, 426, 427, 428, 429, 431, 432, 433, 435, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 448, 452, 453, 454, 455, 460, 461, 464, 465, 466, 469, 470, 471, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 487, 488, 489, 490, 491, 492, 493, 494, 502, 503, 506, 508, 509, 510, 511, 512, 513, 514, 515, 517, 519, 520, 521, 523, 529, 530, 532, 533, 534, 536, 537, 538, 542, 544, 545, 546, 547, 548, 550, 551, 554, 555, 558, 559, 560, 561, 564, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 585, 587, 588, 589, 590, 591, 594, 595, 596, 597, 598, 599, 600, 601, 603, 605, 606, 607, 608, 609, 610, 611, 612, 613, 615, 617, 618, 619, 620, 621, 623, 625, 626, 627, 628, 629, 630, 631, 634, 636, 638, 639, 642, 643, 644, 645, 646, 650, 651, 654, 655, 657, 658, 659, 661, 662, 663, 664, 665, 666, 668, 671, 672, 673, 674, 675, 676, 677, 679, 680, 681, 682, 683, 684, 686, 687, 688, 690, 692, 693, 695, 696, 698, 699, 700, 701, 703, 704, 706, 710, 713, 714, 716, 717, 718, 719, 721, 722, 723, 724, 725, 727, 729, 730, 731, 732, 733, 734, 736, 737, 738, 740, 741, 745, 746, 747, 748, 751, 752, 754, 758, 760, 762, 764, 765, 766, 767, 770, 771, 772, 774, 775, 778, 780, 782, 783, 784, 785, 789, 791, 792, 793, 794, 795, 796, 797, 798, 799, 801, 803, 806, 807, 808, 811, 812, 813, 814, 816, 818, 820, 821, 822, 823, 824, 826, 828, 830, 831, 832, 834, 836, 837, 839, 840, 841, 844, 845, 846, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 876, 877, 879, 880, 882, 883, 884, 886, 887, 888, 890, 891, 892, 893, 894, 895, 897, 898, 899, 903, 904, 905, 906, 907, 909, 910, 911, 912, 913, 914, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 933, 937, 939, 940, 942, 943, 944, 946, 947, 948, 949, 950, 951, 952, 953, 954, 956, 957, 958, 960, 961, 962, 963, 965, 967, 968, 971, 972, 973, 974, 975, 976, 977, 978, 980, 981, 982, 983, 984, 985, 986, 988, 990, 991, 992, 995, 998, 999, 1000, 1001, 1002, 1004, 1005, 1007, 1008, 1009, 1010, 1012, 1013, 1014, 1016, 1018, 1021, 1022, 1024, 1025, 1026, 1027, 1028, 1029, 1033, 1034, 1035, 1036, 1038, 1039, 1041, 1042, 1043, 1044, 1046, 1047, 1048, 1050, 1051, 1052, 1055, 1057, 1058, 1059, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1069, 1070, 1072, 1074, 1075, 1077, 1078, 1081, 1082, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1100, 1101, 1103, 1105, 1106, 1107, 1108, 1109, 1111, 1112, 1113, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1128, 1129, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1139, 1140, 1141, 1143, 1144, 1145, 1147, 1148, 1149, 1151, 1153, 1155, 1156, 1157, 1160, 1161, 1162, 1163, 1164, 1166, 1167, 1168, 1169, 1171, 1172, 1173, 1175, 1177, 1178, 1179, 1180, 1181, 1184, 1185, 1186, 1187, 1188, 1190, 1191, 1192, 1194, 1195, 1196, 1198, 1199, 1200, 1201, 1203, 1208, 1209, 1212, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1231, 1232, 1233, 1234, 1236, 1237, 1238, 1240, 1241, 1242, 1243, 1244, 1246, 1247, 1249, 1250, 1251, 1252, 1253, 1255, 1256, 1258, 1259, 1260, 1261, 1262, 1264, 1266, 1267, 1268, 1269, 1270, 1272, 1275, 1276, 1277, 1280, 1281, 1283, 1284, 1286, 1287, 1288, 1289, 1291, 1292, 1293, 1294, 1295, 1296, 1298, 1299, 1301, 1303, 1305, 1306, 1307, 1308, 1311, 1312, 1314, 1315, 1319, 1320, 1322, 1323, 1324, 1325, 1326, 1327, 1330, 1331, 1332, 1333, 1334, 1335, 1337, 1338, 1340, 1342, 1343, 1344, 1345, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1379, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1390, 1392, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1412, 1413, 1415, 1418, 1419, 1420, 1421, 1422, 1423, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1433, 1434, 1435, 1437, 1438, 1440, 1441, 1442, 1444, 1445, 1446, 1448, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1460, 1461, 1462, 1463, 1465, 1466, 1467, 1468, 1470, 1471, 1472, 1473, 1474, 1477, 1479, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1493, 1496, 1497, 1498, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1514, 1515, 1516, 1517, 1518, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1531, 1532, 1533, 1535, 1536, 1538, 1540, 1541, 1543, 1544, 1545, 1546, 1552, 1553, 1554, 1556, 1558, 1560, 1562, 1563, 1564, 1565, 1567, 1568, 1569, 1570, 1574, 1576, 1577, 1579, 1580, 1581, 1582, 1583, 1585, 1587, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1602, 1603, 1604, 1606, 1607, 1608, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1618, 1619, 1621, 1622, 1624, 1625, 1626, 1627, 1628, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1649, 1650, 1651, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1671, 1674, 1676, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1689, 1692, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1732, 1733, 1734, 1736, 1737, 1738, 1739, 1740, 1742, 1743, 1744, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1763, 1764, 1765, 1766, 1769, 1770, 1771, 1774, 1775, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1786, 1787, 1789, 1790, 1793, 1794, 1796, 1798, 1799, 1801, 1802, 1804, 1805, 1809, 1810, 1811, 1813, 1815, 1816, 1817, 1818, 1819, 1821, 1822, 1823, 1824, 1825, 1827, 1828, 1830, 1831, 1832, 1835, 1837, 1838, 1839, 1840, 1841, 1843, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1859, 1860, 1861, 1863, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1895, 1896, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1908, 1909, 1910, 1911, 1912, 1913, 1915, 1916, 1917, 1918, 1920, 1921, 1922, 1923, 1925, 1926, 1927, 1930, 1931, 1932, 1933, 1935, 1937, 1938, 1939, 1942, 1943, 1944, 1947, 1948, 1950, 1951, 1952, 1953, 1955, 1956, 1957, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1969, 1970, 1972, 1974, 1976, 1980, 1981, 1982, 1983, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1996, 1998, 2000, 2001, 2002, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2018, 2019, 2020, 2021, 2022, 2023, 2025, 2026, 2027, 2028, 2030, 2031, 2033, 2034, 2036, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2046, 2048, 2049, 2050, 2053, 2054, 2057, 2058, 2059, 2060, 2061, 2062, 2064, 2065, 2066, 2068, 2070, 2071, 2072, 2073, 2076, 2077, 2078, 2079, 2081, 2083, 2084, 2085, 2086, 2087, 2089, 2090, 2091, 2092, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2104, 2105, 2106, 2107, 2109, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2119, 2120, 2121, 2122, 2125, 2126, 2127, 2128, 2131, 2132, 2135, 2137, 2138, 2139, 2140, 2143, 2145, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2155, 2156, 2157, 2158, 2159, 2161, 2164, 2165, 2166, 2167, 2169, 2171, 2173, 2174, 2176, 2178, 2179, 2181, 2182, 2183, 2184, 2185, 2186, 2188, 2189, 2190, 2191, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2204, 2205, 2206, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2218, 2219, 2220, 2221, 2223, 2224, 2225, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2235, 2236, 2237, 2238, 2239, 2241, 2242, 2243, 2245, 2246, 2248, 2249, 2251, 2252, 2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2273, 2274, 2276, 2277, 2282, 2284, 2285, 2287, 2288, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2302, 2303, 2305, 2306, 2307, 2308, 2311, 2312, 2313, 2315, 2316, 2317, 2318, 2320, 2321, 2323, 2324, 2325, 2326, 2328, 2331, 2332, 2333, 2334, 2335, 2336, 2338, 2340, 2342, 2344, 2345, 2346, 2347, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2357, 2358, 2359, 2360, 2361, 2364, 2365, 2368, 2370, 2371, 2372, 2374, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2384, 2385, 2386, 2387, 2388, 2389, 2391, 2393, 2396, 2399, 2401, 2402, 2404, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2415, 2416, 2417, 2418, 2421, 2422, 2423, 2427, 2428, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2439, 2440, 2442, 2443, 2444, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2463, 2464, 2465, 2466, 2468, 2469, 2470, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2482, 2484, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495, 2498, 2499, 2500, 2501, 2502, 2504, 2506, 2507, 2508, 2511, 2513, 2514, 2516, 2519, 2521, 2522, 2524, 2525, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2538, 2539, 2540, 2541, 2543, 2544, 2548, 2549, 2550, 2551, 2554, 2555, 2556, 2561, 2562, 2563, 2564, 2566, 2567, 2568, 2569, 2572, 2574, 2575, 2576, 2577, 2578, 2579, 2581, 2582, 2583, 2584, 2587, 2589, 2590, 2591, 2592, 2594, 2595, 2596, 2597, 2598, 2599, 2600, 2601, 2602, 2604, 2606, 2610, 2612, 2614, 2615, 2616, 2617, 2618, 2621, 2623, 2625, 2626, 2628, 2629, 2630, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2643, 2644, 2645, 2646, 2647, 2648, 2649, 2650, 2651, 2653, 2654, 2656, 2657, 2658, 2661, 2662, 2663, 2666, 2667, 2668, 2669, 2671, 2673, 2675, 2676, 2678, 2680, 2682, 2683, 2685, 2687, 2688, 2690, 2691, 2692, 2693, 2695, 2696, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2709, 2710, 2711, 2712, 2714, 2715, 2716, 2718, 2719, 2720, 2721, 2722, 2724, 2725, 2727, 2728, 2731, 2732, 2734, 2736, 2737, 2738, 2739, 2741, 2742, 2743, 2744, 2745, 2746, 2749, 2750, 2752, 2754, 2755, 2756, 2757, 2758, 2759, 2763, 2764, 2765, 2766, 2767, 2768, 2772, 2773, 2774, 2777, 2778, 2779, 2780, 2782, 2783, 2784, 2785, 2786, 2787, 2788, 2790, 2792, 2793, 2795, 2796, 2797, 2798, 2799, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2810, 2811, 2812, 2814, 2815, 2816, 2818, 2819, 2821, 2822, 2823, 2824, 2825, 2826, 2827, 2829, 2830, 2831, 2833, 2834, 2835, 2836, 2837, 2838, 2839, 2841, 2842, 2843, 2845, 2846, 2847, 2848, 2849, 2850, 2851, 2852, 2853, 2854, 2855, 2856, 2857, 2858, 2860, 2861, 2863, 2864, 2865, 2866, 2868, 2869, 2871, 2872, 2873, 2875, 2876, 2877, 2878, 2879, 2880, 2881, 2882, 2883, 2884, 2889, 2890, 2892, 2895, 2896, 2897, 2898, 2899, 2900, 2903, 2904, 2905, 2907, 2910, 2911, 2912, 2913, 2914, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923, 2924, 2925, 2926, 2929, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2938, 2940, 2941, 2942, 2943, 2945, 2946, 2947, 2949, 2950, 2951, 2952, 2953, 2955, 2957, 2958, 2959, 2960, 2962, 2964, 2965, 2967, 2968, 2969, 2970, 2972, 2973, 2974, 2976, 2977, 2978, 2979, 2980, 2981, 2983, 2984, 2985, 2986, 2987, 2990, 2991, 2992, 2993, 2995, 2997, 2998, 2999, 3000, 3001, 3003, 3004, 3005, 3007, 3008, 3009, 3010, 3011, 3012, 3019, 3020, 3021, 3023, 3024, 3026, 3027, 3028, 3029, 3032, 3035, 3036, 3037, 3038, 3039, 3041, 3042, 3044, 3045, 3046, 3047, 3048, 3049, 3050, 3052, 3055, 3056, 3057, 3058, 3059, 3061, 3062, 3068, 3069, 3070, 3071, 3073, 3075, 3076, 3077, 3078, 3079, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3094, 3095, 3097, 3098, 3099, 3100, 3101, 3102, 3103, 3105, 3106, 3107, 3108, 3109, 3110, 3112, 3113, 3114, 3115, 3116, 3118, 3119, 3120, 3122, 3123, 3124, 3125, 3127, 3128, 3129, 3130, 3131, 3134, 3135, 3136, 3137, 3138, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3148, 3150, 3152, 3153, 3156, 3158, 3160, 3161, 3163, 3166, 3167, 3168, 3169, 3171, 3172, 3174, 3175, 3176, 3177, 3179, 3181, 3182, 3183, 3186, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3197, 3198, 3199, 3200, 3201, 3203, 3204, 3205, 3206, 3208, 3209, 3211, 3215, 3217, 3218, 3222, 3223, 3225, 3226, 3227, 3228, 3229, 3230, 3231, 3235, 3236, 3237, 3240, 3241, 3244, 3246, 3247, 3248, 3249, 3251, 3252, 3253, 3254, 3255, 3256, 3257, 3259, 3261, 3262, 3263, 3264, 3265, 3266, 3268, 3269, 3271, 3272, 3274, 3275, 3277, 3278, 3280, 3281, 3283, 3284, 3285, 3286, 3287, 3288, 3290, 3291, 3292, 3293, 3294, 3296, 3297, 3298, 3299, 3300, 3301, 3302, 3303, 3304, 3306, 3307, 3309, 3312, 3313, 3316, 3317, 3321, 3322, 3324, 3325, 3326, 3327, 3331, 3332, 3333, 3334, 3335, 3336, 3339, 3340, 3342, 3343, 3344, 3345, 3347, 3349, 3350, 3351, 3353, 3356, 3358, 3360, 3362, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3376, 3377, 3378, 3382, 3383, 3385, 3386, 3387, 3388, 3389, 3390, 3392, 3396, 3397, 3399, 3401, 3404, 3406, 3407, 3408, 3409, 3410, 3413, 3414, 3415, 3416, 3417, 3418, 3419, 3423, 3425, 3426, 3428, 3429, 3430, 3431, 3432, 3433, 3434, 3437, 3438, 3439, 3440, 3441, 3443, 3444, 3445, 3446, 3447, 3448, 3449, 3452, 3453, 3454, 3456, 3457, 3459, 3462, 3464, 3467, 3469, 3471, 3472, 3480, 3481, 3485, 3486, 3488, 3492, 3493, 3495, 3498, 3500, 3501, 3502, 3503, 3505, 3506, 3508, 3509, 3510, 3511, 3512, 3513, 3518, 3519, 3520, 3521, 3522, 3523, 3524, 3525, 3527, 3528, 3529, 3530, 3531, 3533, 3534, 3535, 3537, 3538, 3539, 3540, 3541, 3542, 3543, 3546, 3547, 3548, 3549, 3550, 3552, 3553, 3554, 3555, 3556, 3557, 3558, 3559, 3560, 3561, 3562, 3563, 3564, 3565, 3567, 3568, 3570, 3571, 3572, 3574, 3575, 3577, 3578, 3580, 3581, 3582, 3586, 3587, 3588, 3589, 3590, 3591, 3592, 3593, 3594, 3595, 3597, 3598, 3600, 3601, 3602, 3603, 3604, 3605, 3606, 3607, 3608, 3609, 3610, 3611, 3612, 3613, 3615, 3616, 3617, 3618, 3619, 3620, 3621, 3623, 3624, 3625, 3627, 3628, 3631, 3632, 3633, 3634, 3635, 3636, 3638, 3639, 3640, 3641, 3642, 3643, 3644, 3647, 3648, 3650, 3653, 3655, 3656, 3657, 3658, 3659, 3660, 3661, 3662, 3663, 3665, 3666, 3669, 3670, 3672, 3673, 3674, 3675, 3676, 3677, 3679, 3681, 3682, 3683, 3684, 3687, 3688, 3689, 3693, 3694, 3695, 3696, 3697, 3698, 3699, 3701, 3702, 3703, 3705, 3706, 3707, 3709, 3710, 3711, 3712, 3713, 3715, 3717, 3718, 3719, 3720, 3722, 3724, 3725, 3726, 3727, 3728, 3729, 3730, 3731, 3732, 3733, 3734, 3735, 3736, 3737, 3739, 3741, 3742, 3743, 3744, 3746, 3747, 3748, 3749, 3750, 3751, 3753, 3754, 3755, 3756, 3757, 3758, 3759, 3761, 3762, 3763, 3764, 3765, 3766, 3767, 3768, 3772, 3773, 3775, 3776, 3777, 3778, 3779, 3780, 3782, 3783, 3784, 3785, 3786, 3787, 3788, 3789, 3790, 3791, 3792, 3794, 3797, 3798, 3800, 3801, 3802, 3803, 3804, 3805, 3806, 3807, 3808, 3810, 3811, 3813, 3814, 3818, 3819, 3820, 3823, 3824, 3826, 3829, 3830, 3832, 3833, 3834, 3835, 3836, 3838, 3839, 3842, 3843, 3845, 3847, 3849, 3850, 3851, 3853, 3854, 3857, 3858, 3859, 3860, 3862, 3864, 3865, 3872, 3873, 3875, 3876, 3877, 3878, 3880, 3881, 3882, 3883, 3885, 3887, 3888, 3889, 3891, 3894, 3896, 3897, 3898, 3899, 3900, 3901, 3903, 3904, 3908, 3909, 3910, 3912, 3913, 3914, 3917, 3919, 3920, 3921, 3923, 3925, 3927, 3928, 3929, 3932, 3934, 3935, 3936, 3937, 3941, 3942, 3943, 3944, 3946, 3948, 3950, 3952, 3953, 3954, 3955, 3958, 3959, 3961, 3962, 3964, 3966, 3967, 3968, 3970, 3971, 3972, 3973, 3976, 3977, 3978, 3980, 3981, 3983, 3985, 3986, 3988, 3989, 3990, 3992, 3993, 3995, 3996, 3997, 3998, 4000, 4001, 4002, 4004, 4005, 4006, 4008, 4009, 4011, 4013, 4015, 4016, 4017, 4018, 4019, 4021, 4022, 4023, 4026, 4028, 4029, 4030, 4032, 4033, 4034, 4036, 4038, 4041, 4043, 4045, 4048, 4049, 4052, 4053, 4054, 4056, 4058, 4059, 4060, 4061, 4062, 4063, 4064, 4065, 4066, 4068, 4069, 4070, 4071, 4072, 4074, 4075, 4076, 4077, 4078, 4079, 4080, 4082, 4083, 4085, 4087, 4088, 4090, 4092, 4093, 4094, 4096, 4098, 4099, 4101, 4102, 4106, 4107, 4110, 4112, 4114, 4118, 4119, 4120, 4121, 4123, 4124, 4125, 4128, 4129, 4130, 4132, 4133, 4135, 4138, 4139, 4141, 4142, 4143, 4144, 4146, 4147, 4148, 4149, 4150, 4151, 4153, 4155, 4156, 4157, 4159, 4160, 4161, 4163, 4164, 4165, 4166, 4167, 4169, 4172, 4173, 4174, 4175, 4176, 4179, 4180, 4181, 4184, 4187, 4188, 4189, 4191, 4199, 4200, 4201, 4202, 4204, 4205, 4208, 4209, 4210, 4212, 4213, 4217, 4218, 4219, 4220, 4221, 4222, 4223, 4224, 4226, 4227, 4228, 4229, 4230, 4232, 4233, 4234, 4237, 4238, 4241, 4242, 4244, 4245, 4246, 4247, 4248, 4249, 4250, 4251, 4252, 4253, 4254, 4255, 4257, 4258, 4260, 4262, 4264, 4265, 4266, 4267, 4268, 4269, 4270, 4271, 4272, 4273, 4274, 4275, 4276, 4277, 4278, 4279, 4281, 4282, 4283, 4284, 4285, 4286, 4288, 4289, 4291, 4293, 4294, 4295, 4296, 4297, 4298, 4299, 4301, 4302, 4303, 4304, 4305, 4309, 4310, 4311, 4315, 4316, 4318, 4320, 4322, 4323, 4324, 4325, 4326, 4327, 4328, 4329, 4330, 4331, 4332, 4334, 4335, 4336, 4337, 4338, 4339, 4340, 4341, 4342, 4343, 4344, 4346, 4347, 4349, 4350, 4351, 4352, 4354, 4355, 4356, 4357, 4358, 4359, 4360, 4362, 4363, 4364, 4365, 4367, 4369, 4370, 4371, 4372, 4373, 4374, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4383, 4384, 4385, 4386, 4387, 4388, 4390, 4392, 4393, 4394, 4395, 4396, 4397, 4398, 4399, 4400, 4401, 4402, 4403, 4404, 4405, 4406, 4407, 4409, 4410, 4411, 4413, 4414, 4415, 4416, 4417, 4419, 4421, 4422, 4423, 4424, 4425, 4426, 4429, 4430, 4431, 4432, 4433, 4434, 4435, 4436, 4437, 4439, 4440, 4442, 4443, 4444, 4446, 4448, 4449, 4450, 4451, 4453, 4454, 4455, 4456, 4457, 4459, 4461, 4462, 4463, 4464, 4465, 4466, 4469, 4470, 4471, 4474, 4475, 4476, 4478, 4479, 4480, 4483, 4484, 4485, 4486, 4487, 4489, 4490, 4492, 4493, 4494, 4495, 4496, 4499, 4500, 4501, 4502, 4503, 4504, 4507, 4509, 4510, 4511, 4513, 4514, 4517, 4520, 4521, 4522, 4525, 4526, 4527, 4529, 4530, 4531, 4532, 4534, 4535, 4536, 4537, 4538, 4539, 4540, 4543, 4544, 4545, 4547, 4549, 4550, 4551, 4552, 4553, 4554, 4555, 4556, 4557, 4558, 4559, 4561, 4563, 4565, 4566, 4567, 4568, 4569, 4570, 4571, 4574, 4575, 4576, 4577, 4578, 4579, 4580, 4581, 4582, 4583, 4584, 4586, 4588, 4589, 4590, 4591, 4592, 4593, 4594, 4595, 4598, 4599, 4601, 4602, 4603, 4604, 4605, 4606, 4607, 4609, 4610, 4611, 4613, 4614, 4615, 4617, 4618, 4619, 4621, 4623, 4625, 4626, 4627, 4628, 4630, 4631, 4632, 4633, 4634, 4635, 4638, 4639, 4640, 4641, 4642, 4643, 4644, 4647, 4648, 4649, 4650, 4651, 4653, 4654, 4655, 4657, 4658, 4659, 4660, 4661, 4662, 4663, 4664, 4666, 4667, 4668, 4669, 4670, 4671, 4672, 4676, 4677, 4678, 4680, 4681, 4683, 4684, 4688, 4689, 4691, 4692, 4694, 4695, 4696, 4697, 4698, 4700, 4701, 4703, 4705, 4706, 4707, 4708, 4709, 4712, 4713, 4716, 4717, 4718, 4719, 4720, 4721, 4722, 4723, 4724, 4725, 4726, 4727, 4729, 4730, 4731, 4733, 4734, 4735, 4738, 4739, 4741, 4742, 4743, 4744, 4745, 4746, 4747, 4748, 4749, 4750, 4752, 4753, 4754, 4755, 4756, 4757, 4761, 4762, 4763, 4764, 4765, 4766, 4767, 4768, 4769, 4770, 4773, 4774, 4775, 4776, 4778, 4780, 4781, 4782, 4783, 4784, 4785, 4786, 4787, 4788, 4790, 4791, 4792, 4793, 4794, 4796, 4797, 4798, 4800, 4802, 4804

In [ ]:
import datamapplot
import numpy as np
import matplotlib

matplotlib.rcParams["figure.dpi"] = 300

fig,ax = datamapplot.create_plot(
    filtered_embeddings,
    formatted_labels,
    figsize=(15,12),
    title="Top 40 Topics Visualization",
    )